### ISSUE TITLE
CentOS 7 Failed to Boot (Corrupted Files)

### ISSUE THREAD

**Issue by ChrisMag18** [griddb/griddb_nosql#103]
Guys i have CentOS 7 with Matrix-Synapse Installed on it. Last week it shut-down and unable to boot again.
1. How can i recover my CentOS 7?
2. How to utilize the same credentials on the old instance to the newly installed instance?
3. Upon checking all files and data are intact in /opt also on /etc.

Please help...

Thanks guys...

**Comment by ChrisMag18** [comment]
Is there anyone out there who can help me please... I need your expertise please... 

Thanks and God Bless...

**Comment by knonomura** [comment]
Your issue is opened in griddb/griddb_nosql repository,
but I guess it is another topic.

**Comment by knonomura** [comment]
I close this issues as it is not related to this repository.
