### ISSUE TITLE
Adres wijziging

### ISSUE THREAD

**Issue by centurionjuristen** [griddb/griddb_nosql#105]
Hi Jonathan,

Het adres is gewijzigd ban Koninginneweg naar:

Frans van Mierisstraat 27 - 3, 1071 RJ Amsterdam 

Kan je dat doorvoeren op de website. Alvast dank.

**Comment by knonomura** [comment]
Thank you for your access.

Your issue is opened in griddb/griddb_nosql repository,
but I guess your operation is wrong.

**Comment by knonomura** [comment]
I close this issues as it is not related to this repository.
