### ISSUE TITLE
DVWA problem

### ISSUE THREAD

**Issue by mohammed1997010** [griddb/griddb_nosql#107]
Hello Friends 
I have turned the  allow_url_include --> On but it's still Disabled is there another php.ini I have to edit....

I'm using kali linux
php 7.3
and apache2

![Screenshot from 2019-05-07 18-26-45](https://user-images.githubusercontent.com/47889454/57312579-82309b00-70f6-11e9-876e-a37a0d0f15f2.png)

**Comment by knonomura** [comment]
Your issue is opened in griddb/griddb_nosql repository,
but I guess it is another topic.

**Comment by knonomura** [comment]
I close this issues as it is not related to this repository.
