### ISSUE TITLE
filter error

### ISSUE THREAD

**Issue by chandan4028** [griddb/griddb_nosql#112]
Uncaught Error: Template parse errors:
TypeError: Cannot read property 'toUpperCase' of undefined ("
      </thead>
      <tbody>
        <tr [ERROR ->]*ngFor="let client of clients | filterPipe: {firstName: searchText}; let i=index; | paginate: { items"): ng:///AppModule/AppComponent.html@48:12
Parser Error: Unexpected token |, expected identifier, keyword, or string at column 75 in [let client of clients | filterPipe: {firstName: searchText}; let i=index; | paginate: { itemsPerPage: 30, currentPage: p }  ] in ng:///AppModule/AppComponent.html@48:12 ("tName: searchText}; let i=index; | paginate: { itemsPerPage: 30, currentPage: p }  ">
          <td>[ERROR ->]{{client.id}}</td>
        
          <td>{{client.firstName}}</td>
"): ng:///AppModule/AppComponent.html@49:14
Parser Error: Unexpected token |, expected identifier, keyword, or string at column 75 in [let client of clients | filterPipe: {firstName: searchText}; let i=index; | paginate: { itemsPerPage: 30, currentPage: p }  ] in ng:///AppModule/AppComponent.html@48:12 ("
          <td>{{client.id}}</td>
        
          <td>[ERROR ->]{{client.firstName}}</td>
          <td>{{client.lastName}}</td>
          <td>{{client.company}}</td"): ng:///AppModule/AppComponent.html@51:14
Parser Error: Unexpected token |, expected identifier, keyword, or string at column 75 in [let client of clients | filterPipe: {firstName: searchText}; let i=index; | paginate: { itemsPerPage: 30, currentPage: p }  ] in ng:///AppModule/AppComponent.html@48:12 ("
        
          <td>{{client.firstName}}</td>
          <td>[ERROR ->]{{client.lastName}}</td>
          <td>{{client.company}}</td>
          <td>{{client.email}}</td>
"): ng:///AppModule/AppComponent.html@52:14
Parser Error: Unexpected token |, expected identifier, keyword, or string at column 75 in [let client of clients | filterPipe: {firstName: searchText}; let i=index; | paginate: { itemsPerPage: 30, currentPage: p }  ] in ng:///AppModule/AppComponent.html@48:12 ("
          <td>{{client.firstName}}</td>
          <td>{{client.lastName}}</td>
          <td>[ERROR ->]{{client.company}}</td>
          <td>{{client.email}}</td>
          <td>{{client.city}}</td>
"): ng:///AppModule/AppComponent.html@53:14
Parser Error: Unexpected token |, expected identifier, keyword, or string at column 75 in [let client of clients | filterPipe: {firstName: searchText}; let i=index; | paginate: { itemsPerPage: 30, currentPage: p }  ] in ng:///AppModule/AppComponent.html@48:12 ("
          <td>{{client.lastName}}</td>
          <td>{{client.company}}</td>
          <td>[ERROR ->]{{client.email}}</td>
          <td>{{client.city}}</td>
        </tr>
"): ng:///AppModule/AppComponent.html@54:14
Parser Error: Unexpected token |, expected identifier, keyword, or string at column 75 in [let client of clients | filterPipe: {firstName: searchText}; let i=index; | paginate: { itemsPerPage: 30, currentPage: p }  ] in ng:///AppModule/AppComponent.html@48:12 ("
          <td>{{client.company}}</td>
          <td>{{client.email}}</td>
          <td>[ERROR ->]{{client.city}}</td>
        </tr>
      </tbody>
"):

**Comment by knonomura** [comment]
Your issue is opened in griddb/griddb_nosql repository,
but I guess it is another topic.
I'll close.
