### ISSUE TITLE
Szállítás aloldalon hiba

### ISSUE THREAD

**Issue by herczegdekor** [griddb/griddb_nosql#113]
Szia Ádám!
A szállítás aloldalon ha rászűrök/rákeresek valamire a számlázási név alapján akkor egy nagy fehér "500"-as hibaüzenet ugrik fel. Van valami frissítés ami miatt ez lehet?

**Comment by knonomura** [comment]
Your issue is opened in griddb/griddb_nosql repository,
but I guess it is another topic.

**Comment by knonomura** [comment]
I close this issues as it is not related to this repository.
