### ISSUE TITLE
Getting an error is Actions on google

### ISSUE THREAD

**Issue by Rishab1999** [griddb/griddb_nosql#122]
{
insertId:  "1mk5byef7wgvhj"  
 labels: {
  channel:  "production"   
  querystream:  "GOOGLE_USER"   
  source:  "AOG_REQUEST_RESPONSE"   
 }
 logName:  "projects/mr-pokemon/logs/actions.googleapis.com%2Factions"  
 receiveTimestamp:  "2019-06-08T18:02:59.439668981Z"  
 resource: {
  labels: {…}   
  type:  "assistant_action"   
 }
 severity:  "ERROR"  
 textPayload:  "App returned an HTTP error. State: URL_UNREACHABLE"  
 timestamp:  "2019-06-08T18:02:59.350494779Z"  
 trace:  "projects/31844990969/traces/ABwppHGY5TiiwTCBt5Hj9-rb0pUBC8bhBWXJ9UpDjkBkKR5x5XLfs_qTC2Er7NwgnfPov_ayDuK5CQ"  
}

I am getting this error please help me 
In action console i am also getting an error in stimulator 
"Unexpectedly found template of type 6"

**Comment by knonomura** [comment]
Your issue is opened in griddb/griddb_nosql repository,
but I guess your operation is wrong.

**Comment by knonomura** [comment]
I close this issue.
