### ISSUE TITLE
Fees included in transaction amount

### ISSUE THREAD

**Issue by dejandespotovic** [griddb/griddb_nosql#127]
Due to Mastercard Mandate from July 2018 it is mandatory for us to provide cardholders with detailed information about service charges included in final price paid by Card user for Airline tickets. Transaction is shown as one amount with specification of costs included in transaction amount: 
"Issuers must disclose
the service charge data to cardholders, making it visible
in cardholder billing statements, online account tools,
mobile apps, or other methods designed to inform
cardholders of their purchases"
Up to eight different service charges can be shown per transactions.  Each fee should be consisted from three elements: 
- Service Charge Description  as defined by Mastercard (recommend tbd as string(30)), 
- Amount 
- Currency
Array of service charge fees should be optional array of service charge fee objects within transaction object (similar to transfer-fees[]).

**Comment by dejandespotovic** [comment]
Wrong address.

**Comment by ROSISO** [comment]
TRANSACTION BY VISA  CARD TO


4678 7520 0200 3795

01/22

CVV 140

________________________________
