### ISSUE TITLE
Fixed Assets

### ISSUE THREAD

**Issue by jabo6311** [griddb/griddb_nosql#130]
Cálculo de depreciación acumulada emite el siguiente error cuando se va a completar:

The following errors were encountered: 
AssetNotActive (ID=1000000)

**REMOVE THE TEXT ABOVE BEFORE CREATING THE ISSUE**

**Comment by knonomura** [comment]
Your issue is opened in griddb/griddb_nosql repository,
but I guess it is another topic.

**Comment by ROSISO** [comment]
> Cálculo de depreciación acumulada emite el siguiente error cuando se va a completar:
> 
> The following errors were encountered:
> AssetNotActive (ID=1000000)
> 
> **REMOVE THE TEXT ABOVE BEFORE CREATING THE ISSUE**

ets et contre complet cumputa dex dux
