### ISSUE TITLE
Can jdiameter be used for IPv6 ? java.net.URISyntaxException when using IPv6

### ISSUE THREAD

**Issue by albertpv** [griddb/griddb_nosql#131]
We would like to use jdiameter to reach IPv6 host.

We are having some issues on jdiameter startup (not finding the good configuration even to start a connection to loopback)

The issue happens both trying to use ::1 or [::1] 

A workaround could be using a hostname/FQDN and add resolution of that hostname to an IPv6 address: but my question is: if we do that is expected jdiameter will work fine vs an IPv6 peer? Is the project supporting that scenario?

See attached client-config.xml we used. In that case we get java.net.URISyntaxException
[client-config-ipv6.txt](https://github.com/griddb/griddb_nosql/files/3340091/client-config-ipv6.txt)

**Comment by knonomura** [comment]
Your issue is opened in griddb/griddb_nosql repository,
but I guess it is another topic.

**Comment by knonomura** [comment]
I close this issue as it is not related to this repository.
