### ISSUE TITLE
1XDH0HPC

### ISSUE THREAD

**Issue by ROSISO** [griddb/griddb_nosql#132]

**Comment by ROSISO** [comment]
QY8SR1HE

**Comment by knonomura** [comment]
Your issue is opened in griddb/griddb_nosql repository,
but I guess your operation is wrong.
I will close this issue.

**Comment by shimondoodkin** [comment]
be careful looks like hackers try to attack your repository
 and lure users to another repository with bad code. 
all starts with innocent nice commits like colored titles etc, beautiful texts.. then they add bad code.

**Comment by knonomura** [comment]
@shimondoodkin 
Thank you for your comment.
