### ISSUE TITLE
i m making a chatting app similar to whatsapp,but i m geeting a blank fragment of contact …here is the contact_fragment code

### ISSUE THREAD

**Issue by RC0106** [griddb/griddb_nosql#136]
#ContactFragment
package com.example.letschat;

import android.os.Bundle; import android.view.LayoutInflater; import android.view.View; import android.view.ViewGroup; import android.widget.TextView;

import androidx.annotation.NonNull; import androidx.fragment.app.Fragment; import androidx.recyclerview.widget.LinearLayoutManager; import androidx.recyclerview.widget.RecyclerView;

import com.firebase.ui.database.FirebaseRecyclerAdapter; import com.firebase.ui.database.FirebaseRecyclerOptions; import com.google.firebase.auth.FirebaseAuth; import com.google.firebase.database.DataSna
[LetsChaT2.zip](https://github.com/griddb/griddb_nosql/files/3364888/LetsChaT2.zip)
pshot; import com.google.firebase.database.DatabaseError; import com.google.firebase.database.DatabaseReference; import com.google.firebase.database.FirebaseDatabase; import com.google.firebase.database.ValueEventListener; import com.squareup.picasso.Picasso;

import java.util.Objects;

import de.hdodenhof.circleimageview.CircleImageView;

/** * A simple {@link Fragment} subclass. */ public class ContactsFragment extends Fragment {

private View ContactsView;
private RecyclerView myContactsList;

private DatabaseReference ContactsRef, UsersRef;
private FirebaseAuth mAuth;
public String CurrentUserID;

public ContactsFragment() {
    // Required empty public constructor
}

@Override
public View onCreateView(@NonNull LayoutInflater inflater, ViewGroup container,
                         Bundle savedInstanceState) {
    // Inflate the layout for this fragment

    ContactsView= inflater.inflate(R.layout.fragment_contacts, container, false);

    myContactsList= ContactsView.findViewById(R.id.contacts_list);
    myContactsList.setLayoutManager(new LinearLayoutManager(getContext()));

    mAuth=FirebaseAuth.getInstance();
    CurrentUserID = mAuth.getCurrentUser().getUid();
    //CurrentUserID= Objects.requireNonNull(mAuth.getCurrentUser()).getUid();

    ContactsRef= FirebaseDatabase.getInstance().getReference().child("Contacts");
    UsersRef=FirebaseDatabase.getInstance().getReference().child("User");

    return ContactsView;
}

@Override
public void onStart() {
    super.onStart();
 FirebaseRecyclerOptions<Contacts> options=
            new FirebaseRecyclerOptions.Builder<Contacts>()
            .setQuery(ContactsRef,Contacts.class)
            .build();

    FirebaseRecyclerAdapter<Contacts,ContactsViewHolder> adapter
            =new FirebaseRecyclerAdapter<Contacts, ContactsViewHolder>(options) {
        @Override
        protected void onBindViewHolder(@NonNull final ContactsViewHolder holder, int position, @NonNull Contacts model) {
            String userIDs=getRef(position).getKey();

            assert userIDs != null;
            UsersRef.child(userIDs).addValueEventListener(new ValueEventListener() {
                @Override
                public void onDataChange(@NonNull DataSnapshot dataSnapshot) {

                    if (dataSnapshot.hasChild("image"))
                    {
                        String userImage= Objects.requireNonNull(dataSnapshot.child("image").getValue()).toString();
                        String profileName= Objects.requireNonNull(dataSnapshot.child("name").getValue()).toString();
                        String profileStatus= Objects.requireNonNull(dataSnapshot.child("status").getValue()).toString();

                        holder.userName.setText(profileName);
                        holder.userStatus.setText(profileStatus);
                        Picasso.get().load(userImage).placeholder(R.drawable.profile_image).into(holder.profileImage);

                    }
                    else
                    {
                        String profileName= Objects.requireNonNull(dataSnapshot.child("name").getValue()).toString();
                        String profileStatus= Objects.requireNonNull(dataSnapshot.child("status").getValue()).toString();

                        holder.userName.setText(profileName);
                        holder.userStatus.setText(profileStatus);
                    }
                }

                @Override
                public void onCancelled(@NonNull DatabaseError databaseError) {

                }
            });

        }

        @NonNull
        @Override
        public ContactsViewHolder onCreateViewHolder(@NonNull ViewGroup viewGroup, int i) {
            View view=LayoutInflater.from(viewGroup.getContext()).inflate(R.layout.users_display_layout,viewGroup,false);
            return new ContactsViewHolder(view);
        }
    };
    myContactsList.setAdapter(adapter);
    adapter.startListening();
}

public static class ContactsViewHolder extends RecyclerView.ViewHolder
{
    TextView userName,userStatus;
    CircleImageView profileImage;

    public ContactsViewHolder(@NonNull View itemView) {
        super(itemView);

        userName=itemView.findViewById(R.id.user_profile_name);
        userStatus=itemView.findViewById(R.id.user_status);
        profileImage =itemView.findViewById(R.id.users_profile_image);
    }
}
}

#Contact.java
package com.example.letschat;

public class Contacts { public String name,status,image;

public Contacts()
{

}

public Contacts(String name, String status, String image)
{
    this.name=name;
    this.status=status;
    this.image=image;
}

public String getName() {
    return name;
}

public void setName(String name) {
    this.name = name;
}

public String getStatus() {
    return status;
}

public void setStatus(String status) {
    this.status = status;
}

public String getImage() {
    return image;
}

public void setImage(String image) {
    this.image = image;
}
}

#fragment_contact.xml
<androidx.recyclerview.widget.RecyclerView
    android:id="@+id/contacts_list"
    android:layout_width="match_parent"
    android:layout_height="match_parent" />

**Comment by knonomura** [comment]
Your issue is opened in griddb/griddb_nosql repository,
but I guess it is another topic.
