### ISSUE TITLE
UAT Analyst Test

### ISSUE THREAD

**Issue by nuruldyahb** [griddb/griddb_nosql#137]
[NURUL BUDIANA UAT Analyst Test Result Form.xlsx](https://github.com/griddb/griddb_nosql/files/3380009/NURUL.BUDIANA.UAT.Analyst.Test.Result.Form.xlsx)
.

**Comment by knonomura** [comment]
Your issue is opened in griddb/griddb_nosql repository,
but I guess it is another topic.
So I will close it.
