### ISSUE TITLE
Business use on Motorcycle cover

### ISSUE THREAD

**Issue by CH5198** [griddb/griddb_nosql#140]
I am in the process of testing unacceptable risk and manager referral's on the Auto & General Website. When doing a quotation for a motorcycle the user selects business use which should state that the risk is unacceptable however the user is able to proceed to the last screen and the use is noted as private even though the user initially selected business use.

Steps to reproduce: 
1) Use the link https://autogentest.telesuredigital.co.za
2) Select quotation for a motorcycle and fill in the personal details 
3) Add the motorcycle details and select business use
4) Proceed to the last screen

Issue: The user should get to the screen stating unacceptable risk as the motorcycle use was selected as business however on the last screen the use has been changed to private and the cover is now acceptable.

![image](https://user-images.githubusercontent.com/52826687/61202259-524dd700-a6e7-11e9-9cd2-c6a4221b48d6.png)

![image](https://user-images.githubusercontent.com/52826687/61202287-6265b680-a6e7-11e9-948e-a808186ce443.png)

**Comment by knonomura** [comment]
Your issue is opened in griddb/griddb_nosql repository,
but I guess it is another topic.
So I will close it.
