### ISSUE TITLE
Arduino motors with IR remote

### ISSUE THREAD

**Issue by CrazyAlissa** [griddb/griddb_nosql#141]
Hello, so I am doing a project with a robot and Arduino. I have some LEDs, the Arduino Uno, IR remote and a sheild for motors. I use multithreading for the remote and LEDs and with the remote I control the motors to move forward, backwards, left and right. The only problem is that when I need to go forward the right side of the motors only work at maximum (255), so I can't accelerate. And I know is a problem with the Ir but i doesn't know what to do. 
The Rover library is just the library that give the motors the speed. 
![15633537120285637680823008619486](https://user-images.githubusercontent.com/44976176/61361787-c3c58b00-a889-11e9-9b89-0faa093eafd8.jpg)
![1563353730163754391043405919109](https://user-images.githubusercontent.com/44976176/61361819-d049e380-a889-11e9-8173-f3c4e02c3f68.jpg)
![15633537451946350036705783579894](https://user-images.githubusercontent.com/44976176/61361835-d770f180-a889-11e9-9b23-60b14f51edef.jpg)
![15633537595782363460059471914352](https://user-images.githubusercontent.com/44976176/61361852-dfc92c80-a889-11e9-9827-ba8b15498bc0.jpg)
![15633537735627236506385977952592](https://user-images.githubusercontent.com/44976176/61361878-e9529480-a889-11e9-996e-817c583cb38c.jpg)

**Comment by knonomura** [comment]
Your issue is opened in griddb/griddb_nosql repository,
but I guess it is another topic.
So I will close it.
