### ISSUE TITLE
Makefile error: "No rule to make target `bin/gridstore.jar'"

### ISSUE THREAD

**Issue by yk0310** [griddb/griddb_nosql#15]
Makefile error: "No rule to make target `bin/gridstore.jar'" is occurred.

**Comment by knonomura** [comment]
The "make" command fails since my modification for issue #13.

I modified to create also gridstore.jar with make.
And I modified README.md and GridDB_QuickStartGuide.html.

**Comment by yk0310** [comment]
Thanks. I could compile.
