### ISSUE TITLE
how to get input from user

### ISSUE THREAD

**Issue by fadi9090** [griddb/griddb_nosql#152]
i am still study right now and cant go ahead with the  courise because i have problem cant get input , i try many thing many way and dont know what to do more
please

if someone will check the code and tell me if i have done mistake

[hallo0.zip](https://github.com/griddb/griddb_nosql/files/3493912/hallo0.zip)

**Comment by knonomura** [comment]
Your issue is opened in griddb/griddb_nosql repository,
but I guess it is another topic.
So, I'll close it.

And I guess there are useful information for you in stackoverflow.
For example:
https://stackoverflow.com/questions/20165954/read-c-string-with-scanf
