### ISSUE TITLE
SQL Till Nils

### ISSUE THREAD

**Issue by DraganZE** [griddb/griddb_nosql#153]
[heavenrp.sql - genväg.zip](https://github.com/griddb/griddb_nosql/files/3494012/heavenrp.sql.-.genvag.zip)

LOL

**Comment by knonomura** [comment]
Your issue is opened in griddb/griddb_nosql repository,
but I can't understand your issue.

**Comment by knonomura** [comment]
I close this issue as it is not related to griddb/griddb_nosql repository.
