### ISSUE TITLE
Django - TypeError - NoneType' object is not iterable - Dont understand why Object is being recognized as None

### ISSUE THREAD

**Issue by vibe78** [griddb/griddb_nosql#160]
first question here as I am relatively new to programming, and I have been breaking my head for Days over an error I am getting, which is the following:

The purpose is creating a user to user "messaging" using Django Channels as per an online tutorial which I want to implement to my django project. I have narrowed down the error as a problem with the Auth model I had in place vs how I am querying it, a URL / path syntax Error or a typo? I am lost after so much research.

When I type in localhost:8000/messages/jarturoch in the browser I get the following error:

obj, created = Thread.objects.get_or_new(self.request.user, other_username)
TypeError: 'NoneType' object is not iterable
HTTP GET /messages/vibe 500 [0.06, 127.0.0.1:62182]
 this is the link to the issues  which is more detailed: https://stackoverflow.com/questions/51426359/django-typeerror-nonetype-object-is-not-iterable-dont-understand-why-obje

thank you

**Comment by knonomura** [comment]
Your issue is opened in griddb/griddb_nosql repository,
but I guess your operation is wrong.

**Comment by knonomura** [comment]
I close this issue.
