### ISSUE TITLE
My first coding problem

### ISSUE THREAD

**Issue by MatthewDesmarais** [griddb/griddb_nosql#163]
My code isn't doing what i expect it to do!

@thomasjbradley

**Comment by Matuhh** [comment]
Opowiedz dokładnie

**Comment by knonomura** [comment]
@MatthewDesmarais 
Your issue is opened in griddb/griddb_nosql repository,
but I guess your operation is wrong.

**Comment by thomasjbradley** [comment]
@knonomura Yes, I believe this was a mistake. I had my students create Issues and tag me to learn the process—this being their first time using GitHub. It appears this Issue was created in the wrong location.

Please go ahead and close the Issue.

**Comment by knonomura** [comment]
@thomasjbradley 
Thanks for your comment.
