### ISSUE TITLE
Bí quyết xây nhà tiết kiệm chi phí tối ưu không phải ai cũng biết

### ISSUE THREAD

**Issue by vatlieuanvinh** [griddb/griddb_nosql#167]
Bất kể trong thời gian nào, ai cũng muốn xây nhà tiết kiệm hết mức có thể. Vậy làm thế nào để xây nhà tiết kiệm chi phí tối ưu nhất?
1. Lựa chọn mảnh đất thuận lợi để xây nhà
Trừ những trường hợp bạn có sẵn đất, còn nếu không, muốn tiết kiệm chi phí xây nhà, bạn hãy chú ý những điều sau khi đi mua đất:
- Chọn mảnh đất có hình dáng vuông vứt, bằng phẳng, cao ráo. Tránh những nơi thấp, dễ ngập úng, bạn sẽ tốn thêm chi phí cho việc xây nền cao.
- Tham khảo chuyên gia hoặc những người có hiểu biết về địa chất, tránh mua phải những nơi đất sét, đất nhão, đất địa tầng yếu. Trường hợp rủi ro, bạn sẽ tốn một khoảng chi phí không nhỏ (tăng dao động từ 20–30% so với đất tốt) cho việc gia cố móng như ép cọc, khoan nhồi, đóng cừ tràm. Nếu sau này có ý định sửa nhà, phần móng cũng sẽ lại tiếp tục “ngốn” tiền của bạn.
- Nhớ xem xét kĩ hệ thống thoát nước của khu vực xung quanh, tránh phát sinh chi phí làm cống, ống dẫn.
Bí quyết xây nhà tiết kiệm chi phí tối ưu là lựa chọn mảnh đất thuận lợi
2. Lưu ý vật liệu
Vật liệu là yếu tố quyết định phần lớn liệu bạn có thể xây nhà giá rẻ hay không. Trong khâu sử dụng vật liệu, bạn sẽ chú ý tới vật liệu xây dựng, nước sơn và vật liệu nội thất.
Với vật liệu xây dựng, bên cạnh việc nghiên cứu chất liệu mình ưa chuộng và quan sát giá thành, bạn nên để ý đến vật liệu mới. Lấy ví dụ hiện tại thị trường đang có loại gạch block, được đúc với hỗn hợp xi măng, đá, cát nhưng bằng phương pháp mới. Gạch block được đánh giá bền bỉ, nhưng thân thiện với môi trường hơn gạch nung. Đặc biệt nếu dùng gạch block bạn sẽ giảm được khoảng 30% chi phí. Đây là lựa chọn đáng cân nhắc để xây nhà tiết kiệm chi phí.
Trong phần vật liệu nội thất, một lời khuyên đáng giá là không nên chạy theo mốt. Lấy ví dụ gạch ốp, thiết bị phòng ngủ, nhà vệ sinh… bạn nên mua model cũ. Chẳng ai để ý một thiết kế “thời thượng” trong nhà làm gì, mà việc dùng model cũ (chứ không phải mua đồ cũ) sẽ giúp bạn có được vật liệu tốt với giá thành giảm. Bao giờ model mới ra cũng sẽ khiến model cũ của năm trước xuống giá.
Lưu ý khi chọn thép xây dựng nhà:
Tính toán trước số lượng vật liệu sẽ dùng cùng chi phí theo giá thị trường ở thời điểm hiện tại để kiểm soát được tổng chi phí.
Tham khảo thêm: Tấm cemboard làm nhà tiết kiệm
https://vatlieuanvinh.com/tin-tuc-vat-lieu/xay-nha-tiet-kiem-voi-tam-cemboard/
3. Chọn thiết kế
Thiết kế dĩ nhiên quan trọng vì nó là bộ mặt cho toàn bộ ngôi nhà của bạn về sau. Tuy nhiên, thiết kế cũng ảnh hưởng rất nhiều đến giá trị, mức tiền phải bỏ ra. Đây là điểm đáng lưu tâm cho những người muốn xây nhà giá rẻ.
Một trong những cách xây nhà tiết kiệm hữu hiệu nhất là hãy thiết kế bên trong cho khoa học, tận dụng các bức tường, các chi tiết nhỏ nhất để hỗ trợ chi tiết khác. Lấy ví dụ, bạn có thể tận dụng khoảng không gian bên chân cầu thang để làm bàn tiếp khách. Đây là cách vừa không để phí phần mép cầu thang, vừa tạo cảm giác ấm áp, thân thiện.
Càng tận dụng tốt không gian từ thiết kế, càng ít chi tiết thừa, dĩ nhiên cả số tiền lẫn thời gian thi công sẽ được rút ngắn. Nếu chịu khó sáng tạo, nghiên cứu các kiểu sắp xếp nội thất, đây sẽ là một điểm không nhỏ giúp bạn xây nhà giá rẻ.

**Comment by AnggaSuherman** [comment]
Sorry, please use English.
