### ISSUE TITLE
Open positions section at career page

### ISSUE THREAD

**Issue by mcbjerregaard** [griddb/griddb_nosql#169]
Look at https://issuu.com/careers 
Open positions for Palo Alto are nicely listed, but the open positions under CPH and Berlin are not. I guess that some conditions are set up as to how many positions can appear under each section. Would like the CPH and Berlin positions to be listed in the same way :) 

Thank you for your help <3

**Comment by knonomura** [comment]
Your issue is opened in griddb/griddb_nosql repository,
but I guess it is another topic.
I will close this issue.
