### ISSUE TITLE
DUVIDA PYTHON

### ISSUE THREAD

**Issue by Apolinho** [griddb/griddb_nosql#174]
How can I read a 3x5 table? I can't make a library read ...
![Screenshot_3](https://user-images.githubusercontent.com/56591520/67693420-6bba1c80-f980-11e9-9893-cbdac76d6d19.png)

**Comment by knonomura** [comment]
Your issue is opened in griddb/griddb_nosql repository,
but I guess it is another topic.

 There might be useful information for you in stackoverflow.
https://stackoverflow.com/

**Comment by knonomura** [comment]
I close this issue as it is not related to this repository.
