### ISSUE TITLE
Tax de Company Information no estaría mostrando la sección correcta según  el país del cliente

### ISSUE THREAD

**Issue by dcuelho** [griddb/griddb_nosql#19]
<img width="960" alt="vc taxes" src="https://user-images.githubusercontent.com/26943695/44235854-63adfc80-a181-11e8-96a7-9573f046b57e.png">

**Comment by knonomura** [comment]
Your issue are opened in griddb/griddb_nosql repository,
but I guess it is not related to this repository.

**Comment by knonomura** [comment]
I will close your issue as it is not related to this repository.
