### ISSUE TITLE
Type mismatch

### ISSUE THREAD

**Issue by natashagul** [griddb/griddb_nosql#207]
my line of code is
dialog = SpotsDialog.Builder().setContext(this).setCancelable(false).build()
and error is
Type mismatch: inferred type is android.app.AlertDialog! but androidx.appcompat.app.AlertDialog was expected

i dont understand how to solve it.. kindly guide me

**Comment by ROSISO** [comment]
AlertDialog,Spots#Alert
this( set(   inferred *type. App?compat 
Builder blind this set build #204 #205

**Comment by knonomura** [comment]
Your issue is opened in griddb/griddb_nosql repository,
but I guess it is another topic.
So I close it.
