### ISSUE TITLE
Mederov algorithm d optimal statistics 

### ISSUE THREAD

**Issue by ROHITKUMARBEHERA** [griddb/griddb_nosql#215]
This is a textarea for an issue about griddb/griddb_nosql repository.

***
How to wite a r program... For Mederov algorithm of d optimal statistics

**Comment by knonomura** [comment]
Your issue is opened in griddb/griddb_nosql repository,
but I guess it is another topic.

**Comment by ROHITKUMARBEHERA** [comment]
> Your issue is opened in griddb/griddb_nosql repository,
> but I guess it is another topic.

Tq... For suggestions

**Comment by knonomura** [comment]
I close this issue as it is not related to this repository.
