### ISSUE TITLE
Тук се съдържа програма за светафар

### ISSUE THREAD

**Issue by alexdeshkov** [griddb/griddb_nosql#217]
#define LED_Y 12
#define LED_R 11
#define LED_G 13
int TimeScale_g;

// the setup function runs once when you press reset or power the board
void setup() {
  // initialize digital pin LED_BUILTIN as an output.
  pinMode(LED_G, OUTPUT);
  pinMode(LED_Y, OUTPUT);
  pinMode(LED_R, OUTPUT);
  TimeScale_g = 100;
}

// the loop function runs over and over again forever
void loop() {
  // This is my furst state(1)
  digitalWrite(LED_R, HIGH);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(LED_Y, LOW);   // turn the LED on (HIGH is the voltage level)
  digitalWrite(LED_G, LOW);   // turn the LED on (HIGH is the voltage level)
  delay(20*TimeScale_g);                       // wait for a second
  // This is my second state(2)
  digitalWrite(LED_R, HIGH);    // turn the LED off by making the voltage LOW
  digitalWrite(LED_Y, HIGH);    // turn the LED off by making the voltage LOW
  digitalWrite(LED_G, LOW);    // turn the LED off by making the voltage LOW
  delay(3*TimeScale_g);                       // wait for a second
  // This is my third state(3)
  digitalWrite(LED_R, LOW);    // turn the LED off by making the voltage LOW
  digitalWrite(LED_Y, LOW);    // turn the LED off by making the voltage LOW
  digitalWrite(LED_G, HIGH);    // turn the LED off by making the voltage LOW
  delay(10*TimeScale_g);
  //This is my forth state (4)
  digitalWrite(LED_R, LOW);    // turn the LED off by making the voltage LOW
  digitalWrite(LED_Y, HIGH);    // turn the LED off by making the voltage LOW
  digitalWrite(LED_G, LOW);    // turn the LED off by making the voltage LOW
  delay(3*TimeScale_g);

  
}

**Comment by alexdeshkov** [comment]
Това е прогпама за светофар

**Comment by knonomura** [comment]
Your issue is opened in griddb/griddb_nosql repository,
but I guess your operation is wrong.
I will close this issue as it is not related to this repository.
