### ISSUE TITLE
How do you display the city name using geocoder ?? This is where I'm at 

### ISSUE THREAD

**Issue by salese** [griddb/griddb_nosql#219]
var x = document.getElementById("city");

function getLocation() {
  if (navigator.geolocation) {
    navigator.geolocation.getCurrentPosition(showPosition);
  } else {
    x.innerHTML = "Geolocation is not supported by this browser.";
  }
}

function showPosition(position){

  x.innerHTML = "https://maps.googleapis.com/maps/api/geocode/json?latlng=51.2761022,-114.0452641&key=KEYHERE"
}

**Comment by knonomura** [comment]
Your issue is opened in griddb/griddb_nosql repository,
but I guess it is another topic.
So, I close this issue.
