### ISSUE TITLE
CONTAINER NEWS FREE

### ISSUE THREAD

**Issue by consultcrt** [griddb/griddb_nosql#224]
CONTEINER NEWS FREEE ABOUTS
[WebmailCetificado012020.zip](https://github.com/griddb/griddb_nosql/files/4037005/WebmailCetificado012020.zip)

**Comment by knonomura** [comment]
Your issue is opened in griddb/griddb_nosql repository,
but I guess it is another topic.
So I close it as it is not related to our repository.
