### ISSUE TITLE
how can i make it move smoother?

### ISSUE THREAD

**Issue by BlueDIamondXD** [griddb/griddb_nosql#225]
i am a new pygame game developer and i dont know how to move smoother please help 

    import pygame
    pygame.init()

    screen = pygame.display.set_mode((800, 600))
    pygame.display.set_caption("game")
    x = 50
    y = 50
    width = 60
    height = 60
    vel = 5

    game_over = True
    while game_over:
        pygame.time.delay(100)

        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                game_over = False
        keys = pygame.key.get_pressed()
        if keys[pygame.K_LEFT]:
            x -= vel
        if keys[pygame.K_RIGHT]:
            x += vel
        if keys[pygame.K_UP]:
            y -= vel
        if keys[pygame.K_DOWN]:
            y += vel
        screen.fill((0, 0, 0))
        pygame.draw.rect(screen, (0, 255, 0), (x, y, width, height))
        pygame.display.update()

**Comment by AnasterianSunstrider** [comment]
use lube haha :D

**Comment by knonomura** [comment]
Your issue is opened in griddb/griddb_nosql repository,
but I guess it is another topic.
So I close it as it is not related to our repository.
