### ISSUE TITLE
Android flash

### ISSUE THREAD

**Issue by so1601** [griddb/griddb_nosql#228]
Ik heb een j3 sm20fn recovery staat er op. Ik heb via Odin en via SD-card geprobeerd het geeft aan dat het flashen gelukt is. Maar als ik het opstart blijft het hangen op het samsung scherm. 
Wat kan ik doen?
___________________________________________________________________________________________________________
I have a j3 sm20fn recovery on it. I tried using Odin and from sd card, it indicates that the flashing was successful. But when I start it up, it gets stuck on the Samsung screen.
What can I do?

**Comment by knonomura** [comment]
Your issue is opened in griddb/griddb_nosql repository,
but I guess it is another topic.

**Comment by so1601** [comment]
So where should I go with the issue?

**Comment by knonomura** [comment]
I close this issue as it is not related to griddb/griddb_nosql repository.
