### ISSUE TITLE
Change feed support for realtime analytics

### ISSUE THREAD

**Issue by harshajayaweeraXHJ** [griddb/griddb_nosql#230]
Does GridDB has a change feed feature like in RethinkDB. Since it would be very helpful in change detection and providing real-time analytics.

**Comment by AnggaSuherman** [comment]
GridDB has a trigger function for event notification, but cannot be attached to a query as of now.
Please have a look at the following:

1. API Reference for Trigger function
[GridDB API Reference](http://griddb.org/griddb_nosql/manual/GridDB_API_Reference.html#sec-4)

2. Sample programs
(a)Trigger function via REST
[GridDB Docs](https://griddb.net/en/docs/documents/5-1-17_trigger-rest.php)
(b)Trigger function via JMS
[GridDB Docs](https://griddb.net/en/docs/documents/5-1-18_trigger-jms.php)

Is this enough for your use case?

**Comment by harshajayaweeraXHJ** [comment]
Thanks, Yes I saw that in your Docs. It would be great if you can provide a feature to get queried result also in the trigger endpoint
