### ISSUE TITLE
Show what Staffing company I am logged in to

### ISSUE THREAD

**Issue by jedbom** [griddb/griddb_nosql#237]
A

**Comment by jedbom** [comment]
Maby like this

![image](https://user-images.githubusercontent.com/32383580/73334266-8b592d80-426c-11ea-8400-052287191dc8.png)

**Comment by knonomura** [comment]
Your issue is opened in griddb/griddb_nosql repository,
but I guess it is another topic.

**Comment by jedbom** [comment]
Tnx, Sorry!
