### ISSUE TITLE
Error:Module object is not callable

### ISSUE THREAD

**Issue by shanmukhabhiram** [griddb/griddb_nosql#239]
![IMG_20200201_164403](https://user-images.githubusercontent.com/54545784/73591241-258dcf80-4512-11ea-9fa0-d26f09ed1cb7.jpg)

Why is this error comming and how to remove it the error is in the path for the chrome drivers but the path is correct

**Comment by knonomura** [comment]
Your issue is opened in griddb/griddb_nosql repository,
but I guess it is another topic.
So, I close this issue.
