### ISSUE TITLE
[Usuarios beta Aserta]

### ISSUE THREAD

**Issue by Andrea-Hocelot** [griddb/griddb_nosql#240]
Me pidieron agregar a la lista de beta tester:
Karla: kanieto@aserta.com.mx / iOS 
Norma: nvillaurrutia@aserta.com.mx / iOS 
Juan Carlos Leal:  jcleal@infinitummail.com / iOS
Manuel: mcardenas@aserta.com.mx / iOS
Mariana: marianaimdz@gmail.com / iOS
Daniel: dgalvez@aserta.com.mx / iOS
Ángeles: 
Marco: ya registrado
Juan Carlos Lugo: ya registrado jcl3005@me.com / iOS

**Comment by Andrea-Hocelot** [comment]
Karla: kanieto@aserta.com.mx / iOS
Norma: nvillaurrutia@aserta.com.mx / iOS
Juan Carlos Leal: jcleal@infinitummail.com / iOS
Manuel: mcardenas@aserta.com.mx / iOS
Mariana: marianaimdz@gmail.com / iOS
Daniel: dgalvez@aserta.com.mx / iOS
Ángeles:angeles.zendejas@icloud.com/ios
Marco: ya registrado malejo@aserta.com.mx
Juan Carlos Lugo: ya registrado jcl3005@me.com / iOS

**Comment by ROSISO** [comment]
the eye is sensitive to iron like the hair , when sight is from the value of light and shade is the same
load as effort close their sight . 
what is view by the eye has wight to how important is as wast
