### ISSUE TITLE
Flash a dead phone

### ISSUE THREAD

**Issue by so1601** [griddb/griddb_nosql#241]
I have a SM-J320FN, but no OS. Who can help me with flash an Android on it?
I don't know how to do it.

**Comment by ROSISO** [comment]
flashing nokia opera store, exe. file manager OS upgrade. nokia pc suite file manager nokia e72

**Comment by so1601** [comment]
It is a Samsung device. 
If that is posible, how can I do it?

**Comment by knonomura** [comment]
@so1601 
Your issue is opened in griddb/griddb_nosql repository,
but I guess it is another topic and your operation is wrong.
So, I close this issue.
