### ISSUE TITLE
error while installing pyAudio

### ISSUE THREAD

**Issue by Umashankar1411** [griddb/griddb_nosql#257]
(venv) C:\Users\HP\PycharmProjects\UGT'sChatbot>pip install pyaudio
Collecting pyaudio
  Using cached https://files.pythonhosted.org/packages/ab/42/b4f04721c5c5bfc196ce156b3c768998ef8c0ae3654ed29ea5020c749a6b/PyAudio-0.2.11.tar.gz
Installing collected packages: pyaudio
  Running setup.py install for pyaudio ... error
    Complete output from command "C:\Users\HP\PycharmProjects\UGT'sChatbot\venv\Scripts\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\HP\\AppData\\Local\\Temp\\pip-ins
tall-l476senu\\pyaudio\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\
HP\AppData\Local\Temp\pip-record-50apihj5\install-record.txt --single-version-externally-managed --compile --install-headers "C:\Users\HP\PycharmProjects\UGT'sChatbot\venv\include\site\pyth
on3.7\pyaudio":
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-3.7
    copying src\pyaudio.py -> build\lib.win32-3.7
    running build_ext
    building '_portaudio' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/

    ----------------------------------------
Command ""C:\Users\HP\PycharmProjects\UGT'sChatbot\venv\Scripts\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\HP\\AppData\\Local\\Temp\\pip-install-l476senu\\pyaudio\\
setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\HP\AppData\Local\Temp\pi
p-record-50apihj5\install-record.txt --single-version-externally-managed --compile --install-headers "C:\Users\HP\PycharmProjects\UGT'sChatbot\venv\include\site\python3.7\pyaudio"" failed w
ith error code 1 in C:\Users\HP\AppData\Local\Temp\pip-install-l476senu\pyaudio\

**Comment by knonomura** [comment]
Your issue is opened in griddb/griddb_nosql repository,
but I guess it is another topic.
