### ISSUE TITLE
Twilight Forest issue

### ISSUE THREAD

**Issue by screeck** [griddb/griddb_nosql#261]
Hi. 
I have a problem with my modpack.
When i entered Twilight Forest my Minecraft have crashed . Now when i enter this world i have this communicate.
![15854948481248216780676811412127](https://user-images.githubusercontent.com/58401384/77852777-bc100180-71e0-11ea-8ba7-2104ae722f5d.jpg)

Help. I need this save.

**Comment by Paty14** [comment]
Ok
