### ISSUE TITLE
Azure function with python - SQL Error

### ISSUE THREAD

**Issue by Saifbabrak** [griddb/griddb_nosql#262]
Hi everyone

I just started using azure function where I want to trigger a python script to get, manipulate and insert data into a SQL database. This works fine when I run it at my laptop, but when i run it in azure I get the following error:

Result: Failure
Exception: Error: ('HY000', '[HY000] [Microsoft][ODBC Driver 17 for SQL Server]MAX_PROVS: Error code 0x57 (87) (SQLDriverConnect)')
Stack:   File "/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/dispatcher.py", line 313, in _handle__invocation_request
    call_result = await self._loop.run_in_executor(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/azure-functions-host/workers/python/3.8/LINUX/X64/azure_functions_worker/dispatcher.py", line 434, in __run_sync_func
    return func(**params)
  File "/home/site/wwwroot/HttpExample/__init__.py", line 157, in main
    conn = pyodbc.connect(con_str)

I just can't figure out what the problem is. 

I hope someone can be of help :)

**Comment by knonomura** [comment]
Your issue is opened in griddb/griddb_nosql repository,
but I guess it is another topic.
