### ISSUE TITLE
sudoku solver using stack

### ISSUE THREAD

**Issue by fadi9090** [griddb/griddb_nosql#263]
i have an assignment solve Sudoku backtrack with stack of coordinate i had implement most of it 
the only issue i had cant not implement the solve Sudoku with stack i had try many ways and all give me the same error just looping with out stop
please if someone can help me with the code 
this is my code:
#include <iostream>
#include <fstream>
#include <string>
#include "Stack.h"

using namespace std;

#define UNSINGHED 0

 struct Coordinates {
     int row ;
     int col ;
};

struct sudokuPuzzle {
    int** sudoku;
    int rows;
    int columns;
    Coordinates puzzle;
};
bool UsedInRow(sudokuPuzzle* problem, int rows,int num)
{
    for (int col = 0; col < problem->columns; col++)
        if (problem->sudoku[rows][col] == num)
            return true;
    return false;
}

bool UsedInColumns(sudokuPuzzle* problem, int columns, int num)
{
    for (int j = 0; j < problem->rows; j++)
        if (problem->sudoku[j][columns] == num)
            return true;
    return false;
}

bool UsedInBox(sudokuPuzzle* problem, int rows, int columns,int num)
{
    
    for (int i = 0; i < 3; i++)
        for (int j = 0; j < 3; j++)
            if (problem->sudoku[i + rows][j + columns] == num)
                return true;
    return false;
}

bool matchNumber(sudokuPuzzle* problem, int rows, int columns, int num)
{
    return !UsedInRow(problem,rows, num) &&
        !UsedInColumns(problem,columns, num) &&
        !UsedInBox(problem,rows - rows % 3,
            columns - columns % 3, num) &&
       problem->sudoku[rows][columns] == UNSINGHED;
bool findunsigned(sudokuPuzzle* problem,int &row,int &col) {
    for ( row = 0; row < problem->rows; row++) {
        for ( col = 0; col < problem->columns; col++) {
            if (problem->sudoku[row][col] == UNSINGHED)
                return true;
        }
    }
    return false;
}
void solvesudoku(sudokuPuzzle* problem, int count,bool reverse = true)
{
    Stack<Coordinates> mystack;
    mystack.push(problem->puzzle);

    while (!mystack.isFull())
    {
        count++;
        Coordinates currentstep = mystack.top();
       

         if (!findunsigned(problem, currentstep.row, currentstep.col)) return;

         
            for (int num = 1; num <= 9; num++)
            {
                if (matchNumber(problem, currentstep.row, currentstep.col, num))
                {
                    problem->sudoku[currentstep.row][currentstep.col] = num;
                    mystack.push(Coordinates{ currentstep.row , currentstep.col });
                    break;
                    
                }
             if (num == 9 && !matchNumber(problem,currentstep.row,currentstep.col,num))
                 mystack.pop();   
            }      
    }
    cout << count << endl;
    printPuzzle(problem);
}

sudokuPuzzle* loadPuzzle(string filename) {
    sudokuPuzzle* problem = new sudokuPuzzle();

    ifstream file(filename);

    file >> problem->rows;
    file >> problem->columns;

    problem->puzzle.row = 0;
    problem->puzzle.col = 0;

    problem->sudoku = new int* [problem->rows];
    for (int i = 0; i < problem->rows; i++) {
        problem->sudoku[i] = new int[problem->columns];
    }
    

    for (int i = 0; i < problem->rows; i++) {
        problem->puzzle.col = i;
        for (int j = 0; j < problem->columns; j++) {
            problem->puzzle.row = j;
            file >> problem->sudoku[i][j];
        }
    }

    return problem;
}

**Comment by knonomura** [comment]
Your issue is opened in griddb/griddb_nosql repository,
but I guess it is another topic.

**Comment by fadi9090** [comment]
Its compllosary using stack backtrack and use coordinate to store the position
