### ISSUE TITLE
running Hydrus-1D using python script not working!

### ISSUE THREAD

**Issue by MeisamRezaei** [griddb/griddb_nosql#272]
Hi, I have scrips to run Hydrus in Python 2.7 which I summarized below. It imports hydrus funky and should run hydrus model. But it is not working and executing hydrus project. Can you help me to solve this issue? I could not upload my project here so I provide the link to have look at it.

https://drive.google.com/file/d/11DPKE8_mP4f1GJH1N4oBAZD4oAy9nGWo/view?usp=sharing

 

------------------------------------------
# Run Hydrus in Batch
#==============================================================================

import os
import sys
import numpy
import pylab
import shutil
import distutils.dir_util as dir_util
import linecache
import glob
from Hydrus_Funky import *
from matplotlib.backends.backend_pdf import PdfPages
figlist=[]
figsize=[10,8]
#figsize=[20,10]
dpi=None
pylab.ioff()
font = {'family' : 'monospace',
        'size'   : 11}
pylab.rc('font', **font)
HydrusPath="C:\\Program Files (x86)\\PC-Progress\\Hydrus-1D 4.xx"  # INSTALLATION FOLDER HYDRUS
ExperimentRoot = "C:\\model sistan"
RefProjectPath=os.path.join(ExperimentRoot,'test') # PROJECT FOLDER
OutputPath=os.path.join(ExperimentRoot,'output')
#==============================================================================
# Run Hydrus
#==============================================================================

for iI in range(nI):
#for iI in range(1):
    print('%s,%s'%(iI,nI))

    # Copy Original project
    Postfix='_Temp'
    ReplaceProjectPath=RefProjectPath+Postfix
    
    dir_util.copy_tree(RefProjectPath,ReplaceProjectPath)
    shutil.copy(RefProjectPath+'.h1d',ReplaceProjectPath+'.h1d')

Hydrus_Funky

-------------------------------------------------------------------------

# Hydrus related Functions
#==============================================================================
import os
import numpy
import time
import glob
import copy
import io
import sys
import signal
if sys.version_info.major == 2:
    from StringIO import StringIO
else:
    from io import StringIO

## TOOL

def FindMatches1(A,B):
    nA=A.size
    nB=B.size
    
    A=numpy.ones((nA,nB))*A[:,None]
    B=numpy.ones((nA,nB))*B[None,:]
    A==B
    
    return
    
def FindMatches2(A,B):
    nA=A.size
    nB=B.size
    
    iMatch=numpy.zeros(nA,dtype='int')
    for iA in range(nA):
        iMatch[iA]=numpy.argmin((A[iA]-B)**2)
    
    return iMatch

#==============================================================================
# RUN HYDRUS
#==============================================================================

def runHydrus(path_to_dir,install_dir="C:\\Program Files (x86)\\PC-Progress\\Hydrus-1D 4.xx", guessed_runtime=-1):
    '''
    Author: Van Hoey Stijn
    Run the Hydrus model from within Python
    
    Parameters
    ------------
    guessed_runtime:
        runtime of the model, in seconds (take some seconds more)
    path_to_dir:
        path to the working directory with input/output of Hydrus
    install_dir:
        path to the installation directory of the Hydrus software       
    
    '''
    import os
    import subprocess
    import time
    import glob
    import copy
    
    cdtorun=os.path.join(install_dir,'H1D_CALC')+' '+path_to_dir
    
    print(cdtorun)
    intervalsleeptime = 0.0
    redo=True
    while redo:
        intervalsleeptime = intervalsleeptime+0.5
        proc = subprocess.Popen(cdtorun)
#        proc = subprocess.run(cdtorun)
#        proc = subprocess.call(cdtorun)
        proc = subprocess.Popen(cdtorun, stderr=subprocess.PIPE, stdout=subprocess.PIPE)
        
#        for stdout_line in iter(proc.stdout.readline, ""):
#            yield stdout_line 
#        proc.stdout.close()
        outfilelist_previous = []
        ## Wait for the moment
        if guessed_runtime == -1 :
            # Option 1 : Check
        
            # Option 1A : Check for end of file
            IsFinished=True
            time.sleep(0.3)
            while IsFinished:
                time.sleep(0.1)
                checkfile=os.path.join(path_to_dir,'T_Level.out')
                if os.path.isfile(checkfile):
                    time.sleep(0.1)
                    f=open(checkfile)
                    f.seek(-20, os.SEEK_END) #50 should be enough for the purpose here
                    line = f.readlines()[-1]
                    f.close()
                    if line != 'end\n':
                        IsFinished=True
                    else:
                        IsFinished=False
                        time.sleep(0.05) # To be sure
        
            # Option 1B : Check filesize
            IsFinished=True
            time.sleep(0.3)
            outfilelist = glob.glob(os.path.join(path_to_dir,'*.out'))
            nOut = len(outfilelist)
            checkfilesize_previous= numpy.ones(nOut)*(-1)
                            
            while IsFinished:
                print('Not Finished')
                
                time.sleep(intervalsleeptime)
                
                outfilelist = glob.glob(os.path.join(path_to_dir,'*.out'))
                nOut = len(outfilelist)
                if (len(outfilelist_previous) != nOut):
                    checkfilesize_previous= numpy.ones(nOut)*(-1)
                
                if nOut !=0:
                    checkfilesize = numpy.zeros(nOut)
                    for iOut in range(nOut):
                        checkfilesize[iOut] = os.path.getsize(outfilelist[iOut])
                        print('%s :\t%i\t%i'%(os.path.basename(outfilelist[iOut]),checkfilesize_previous[iOut],checkfilesize[iOut]))

                    if numpy.any(checkfilesize != checkfilesize_previous):
                        IsFinished=True
                        checkfilesize_previous = copy.deepcopy(checkfilesize)
                        outfilelist_previous = copy.deepcopy(outfilelist)
                    else:
                        print('Maybe Finished')
                        IsFinished=False
                        time.sleep(0.3) # To be sure
                        
        else:
            # Option 2 : Sleep
            time.sleep(guessed_runtime) #time nothing is happening to let model run
        print('Finished')
        
        if 'win' in sys.platform:
#            import signal
#            os.kill(proc.pid, signal.CTRL_C_EVENT)
            time.sleep(1.0)
            subprocess.Popen("taskkill /F /T /PID %i"%proc.pid)
            time.sleep(1.0)
            proc.terminate()
        else:
            proc.terminate()
#        
        
        redo=False
                
        #control if sleep was long enough
        #all files with the .out extension need to have 'end' in the last line
        #except of the balance, which has the runtime
        #When doing multiple runs, the calculation time of the first will be reused if this one was too short
        files_in_dir = os.listdir(path_to_dir)
        for file_in_dir in files_in_dir:
            if file_in_dir[-4:]=='.out':
                print(file_in_dir)
                try:
                    f=open(os.path.join(path_to_dir,file_in_dir))
#                    f.seek(-100, os.SEEK_END) #100 should be enough for the purpose here
                    lines = f.readlines()
                    f.close()
                    if len(lines)>0:
                        line = lines[-1]
                        if file_in_dir ==  'Balance.out':             
    #                        print(line)
                            pass
                        elif file_in_dir ==  'Fit.out':
    #                        print(line)
                            pass
                        elif file_in_dir ==  'Irrig.out':
                            pass
                        elif file_in_dir ==  'I_Check.out':
                            pass
                        elif file_in_dir ==  'ChemBal.out':
                            pass
                        else:
                            if line != 'end\n':
                                print('The sleep time was not long enough to perform the entire simulation. The file',file_in_dir,'has not the entire simulation period written.')
                                redo=True
                                time.sleep(0.2)
                except IOError:
                    print(file_in_dir)
                    redo=True
                    time.sleep(2)
                    
                    
        
        check_for_error(path_to_dir)
def check_for_error(path_to_model):
    '''
    Author: Van Hoey Stijn
    Check in model directory for error messages
    '''
    import os
    files_in_dir = os.listdir(path_to_model)
    if 'Error.msg' in files_in_dir:
        raise Exception('ATTENTION: ERROR in model run!')

**Comment by MeisamRezaei** [comment]
Hi, I contacted to the author of Hydrus software about the issue mentioned above.  He stated that "Contrary to the standard computational modules (e.g., h1d_calc.exe), the UnsatChem module (h1d_unsc.exe) needs not only input files from the working project folder, but also four files with inputs for Pitzer's model, i.e., BINARYP.dat, COMP.dat, LAMBDA.dat, and TERNARYP.dat. These files needs to be located in the folder with the exe file."

So I notice that H1D_UNSC should be replaced with H1D_CALC, however all the files are in the same directory but the problem has not been solved.

**Comment by knonomura** [comment]
Your issue is opened in griddb/griddb_nosql repository,
but I guess it is another topic.
So, I close it.
