### ISSUE TITLE
code python word convert to pdf doesn't work

### ISSUE THREAD

**Issue by 666sasuke666** [griddb/griddb_nosql#277]
hi
i have tried a code to convert a word into a pdf andit doesn't work
example

import  sys
import  os
import  comptypes.client

def  word_to_pdf (_in, _out):
    pdf_format_key = 17
    file_in = os.path.abspath (_in)
    file_out = os.path.abspath (_out)
    worddoc = comtypes.client.CreateObject ( 'Word.Application' )
    doc = worddoc.Documents.Open (file_in)
    doc.SaveAs (file_out, FileFormat = pdf_format_key)
    doc.Close ()
    worddoc.Quit ()

destination = sys.argv [ 1 ]
for  file  in os.listdir (destination):
    word_to_pdf (destination + "\\" + file , destination + "\\" + file + ".pdf" )

after that i run it in the comand prompt for for the file word in the folder specified in his path and it show me this

![image](https://user-images.githubusercontent.com/40918736/83116802-f90b4e00-a0d4-11ea-800e-3794b876a06f.png)

**Comment by knonomura** [comment]
Your issue is opened in griddb/griddb_nosql repository,
but I guess it is another topic.

**Comment by balk125** [comment]
I think you have create a virtual environment through your pycham during creating your new project but you downloading  the module int the existing interpreter.
Go to pycham setting and change virtual environment into existing interpreter.

**Comment by knonomura** [comment]
I close this issue as it is not related to this repository.
