### ISSUE TITLE
New Logo/Icon Proposal

### ISSUE THREAD

**Issue by mansya** [griddb/griddb_nosql#29]
Good day sir. I am a graphic designer and i am interested in designing a logo for your good project. I will be doing it as a gift for free. I just need your permission first before I begin my design. Hoping for your positive feedback. Thanks

**Comment by tharun143** [comment]
Yeah, its good to hear such an offer from you. Actually, I need a logo for
a purpose.
Design a logo that could be used by GSoC students in their wrap-up posts
The logo should be productive and creative. Use all your talent.
I need it within 2 days. Hope your logo should be used in further projects.
--
Regards,
Tharun Ravuri,
GitHub <https://github.com/tharun143>||LinkedIn
<https://www.linkedin.com/in/tharun-ravuri-882481167/>||
Quora <https://www.quora.com/profile/Tharun-Ravuri>||Youtube
<https://www.youtube.com/channel/UCG0l2AAg7hkM-1X-5dq4Gjg>||CodeChef
<https://www.codechef.com/users/tharun2468>||
Codeforces <https://codeforces.com/profile/tharun2468>||

**Comment by mansya** [comment]
hi sir. I have completed the logo design for this project. How ? do you like it ? if yes. please tell me. and if there is a change please inform me. I will try my best.
![grid db](https://user-images.githubusercontent.com/33461607/47966147-a0eba180-e081-11e8-84c7-0f9f28e39f5a.png)

**Comment by tharun143** [comment]
Can you explain me about this. IN brief words about the concept. Because I
didn't get you
--
Regards,
Tharun Ravuri,
GitHub <https://github.com/tharun143>||LinkedIn
<https://www.linkedin.com/in/tharun-ravuri-882481167/>||
Quora <https://www.quora.com/profile/Tharun-Ravuri>||Youtube
<https://www.youtube.com/channel/UCG0l2AAg7hkM-1X-5dq4Gjg>||CodeChef
<https://www.codechef.com/users/tharun2468>||
Codeforces <https://codeforces.com/profile/tharun2468>||

**Comment by mansya** [comment]
Database icon is used because this project is database based. and the lock icon is used because this project uses GridDB has a KVS (Key-Value Store). so I took the key icon from the keyword in the word (Key-Value Store).

**Comment by tharun143** [comment]
Wow that's good and also I need another logo for a purpose. Design a logo
that could be used by GSoC students in their wrap-up posts
Create and send it to me. Waiting for your work to see :)
--
Regards,
Tharun Ravuri,
GitHub <https://github.com/tharun143>||LinkedIn
<https://www.linkedin.com/in/tharun-ravuri-882481167/>||
Quora <https://www.quora.com/profile/Tharun-Ravuri>||Youtube
<https://www.youtube.com/channel/UCG0l2AAg7hkM-1X-5dq4Gjg>||CodeChef
<https://www.codechef.com/users/tharun2468>||
Codeforces <https://codeforces.com/profile/tharun2468>||

**Comment by mansya** [comment]
I will do it as soon as possible. please wait sir. :+1:

**Comment by tharun143** [comment]
When can I get that. Please reply me ASAP
--
Regards,
Tharun Ravuri,
GitHub <https://github.com/tharun143>||LinkedIn
<https://www.linkedin.com/in/tharun-ravuri-882481167/>||
Quora <https://www.quora.com/profile/Tharun-Ravuri>||Youtube
<https://www.youtube.com/channel/UCG0l2AAg7hkM-1X-5dq4Gjg>||CodeChef
<https://www.codechef.com/users/tharun2468>||
Codeforces <https://codeforces.com/profile/tharun2468>||

**Comment by AnggaSuherman** [comment]
Hello Guys I think there has been a slight misunderstanding here.
Thank you @mansya , but currently GridDB already has a logo and we are not planning to update it anytime soon.
I believe @tharun143 requires a logo for his project, so please open an issue on his repository instead. 
Thanks guys, hope you can work out the logo.
~CLOSED~
