### ISSUE TITLE
Boka tid Cab Plan appen

### ISSUE THREAD

**Issue by HenrikBeSupport** [griddb/griddb_nosql#39]
Hej.
Boka tid i appen Cabplan/se bokning hade varit bra.

Patric Isberg
Verkstadschef

Hedin Performance Cars AB

Direkt: +46 70 40 8632

**Comment by knonomura** [comment]
It seems you open some issues in griddb/griddb_nosql repository,
but I quess it is another topic.

**Comment by knonomura** [comment]
I close this issue as it is not related to this repository.
