### ISSUE TITLE
Failed to start gsserver

### ISSUE THREAD

**Issue by bhasuanant** [griddb/griddb_nosql#4]
Affter installation tried starting the master node using bin/gs_startnode, no gsserver started.
Log shows followings:
2016-05-03T13:08:09.521+0530 worker 3006 WARNING EVENT_ENGINE [1042:CM_PLATFORM_ERROR] Retrying to resolve address (host=worker, port=10010, trial=1, elapsedMillis=2, reason=Platform error 
Using CentOS 6.3 and gcc version 4.4.7

**Comment by knonomura** [comment]
First, check with the following command to see whether the setting has been configured. 
If the IP address appears, it means that the setting has already been configured.
$ hostname -i

Please refer to Section 2.3.1 Configuration of the Network Environment of the "Quick Start" Guide.

**Comment by bhasuanant** [comment]
Thnx for the reference, i could start the server
