### ISSUE TITLE
Skulle önska möjlighet att ändra ljusstyrka mm på bilderna, ...

### ISSUE THREAD

**Issue by HenrikBeSupport** [griddb/griddb_nosql#45]
Burlin Motor AB
C002003110

Skulle önska möjlighet att ändra ljusstyrka mm på bilderna, är det någon som är möjligt redan som jag har missat? Annars lägger jag det till önskelistan för framtida uppdateringar ;)

**Comment by knonomura** [comment]
Thnk you for your access.

Your issue is opened in griddb/griddb_nosql repository,
but I guess it is another topic.

**Comment by knonomura** [comment]
I close this issue.
