### ISSUE TITLE
Problem with gym surcharges

### ISSUE THREAD

**Issue by fcs2001** [griddb/griddb_nosql#69]
Good morning,
we realized now that many products that have the surcharges, in the gym account does not display them and purchases that make the gym accounts, result with the standard price without the various surcharges.
This is the link of one of these products:
https://www.fightclubstore.com/karategi-bushido-nero.html
Urgent! Thank you

**Comment by fcs2001** [comment]
We also realized that, by logging in as a gym, when you go to research the product, it shows both prices (ie the discounted one and the one to the public).
When you enter the product, only the full price appears, when instead you go to check the cart, the price is discounted, but without surcharge of the relative sizes

**Comment by fcs2001** [comment]
![image](https://user-images.githubusercontent.com/45095675/52628623-58c9ef80-2eb8-11e9-9fb4-87c902afed76.png)
this is what appears inside the cart

**Comment by fcs2001** [comment]
![image](https://user-images.githubusercontent.com/45095675/52628676-6f704680-2eb8-11e9-9c55-a3c0e1b07e8e.png)
this is what appears clicking on the product (although it is logged in as a gym)

**Comment by knonomura** [comment]
I close this issue as it is not related to this repository.
