### ISSUE TITLE
Delete Amazon's Available List

### ISSUE THREAD

**Issue by fcs2001** [griddb/griddb_nosql#70]
![image](https://user-images.githubusercontent.com/45095675/52656538-e0ceea00-2ef6-11e9-9ca0-a59586ebfc5c.png)
Please delete Amazon's list "Available Herostore"

**Comment by knonomura** [comment]
Your issue is opened in griddb/griddb_nosql repository on github.com,
but I guess it is another topic.
I will close this issue as it is not related to this repository.
