### ISSUE TITLE
Problem with product price change

### ISSUE THREAD

**Issue by fcs2001** [griddb/griddb_nosql#72]
Good morning
we tried to modify the product cod. Apr T3W.
When you open the product listing on the site, price changes, photos and description appear regularly.
While if you search for the product in the lists, it still appears with the old changes (price and title). Below the photo of the product (although we have already emptied the cache several times)
![image](https://user-images.githubusercontent.com/45095675/52778387-336aec00-3046-11e9-9852-154eae977bdb.png)

**Comment by knonomura** [comment]
I close this issue as it is not related to this repository.
