### ISSUE TITLE
Brief Recap of sytem errors Feb 14,2019

### ISSUE THREAD

**Issue by forlandoyyz** [griddb/griddb_nosql#73]
Morning Blake, I'm VERY confused. Generaly,  95% not working.

This is what I'm seeing:
Pic 1: BranchUp page shows a green resume posting. 
Pic 2: Shows: Connectivity is in fact operating  
Pic 3:POST LOG in ADMIN: shows very few agents have succesful posts
Pic 4: shows Marion, first agent in Pic 3 – her profile says Psot Pending in Red
Pic 5: shows she does not have autopublish on but there is a Giraffe picture in her page thst is ours.
Alicia Mitchel, 5th down in the post log (pic 3) same issue

Conclusion:
Posts being published as planned: No
ADMIN account Management: Not working, seems geen button working backwards or not working?

What do you think Blake? Please refer to my email for Images.

**Comment by knonomura** [comment]
I close this issue as it is not related to this repository.
