### ISSUE TITLE
Preoperativo GAP'S   

### ISSUE THREAD

**Issue by delcabo** [griddb/griddb_nosql#76]
Al terminar de capturar una bitacora de preoperativo, cuando se le de el boton de enviar bitacora que salga un campo text y que pida nombre de la persona que captura....

porque?:   pues salio que en CA no sera posible tener tantos usarios o saber quien hara el preoperativo tal dia :(   nimodo..  y este campo sera basicamente el nombre que reemplaza el EMPLEADO

para esto se decidio hace un usario "PEStec" (tecnico de pescadero) para que cualquier persona pueda usarlo  para preo de pescadero...

haber como se puede lograr!!
![image](https://user-images.githubusercontent.com/28766240/52804148-57273580-3038-11e9-8404-6f7f52b965fa.png)

**Comment by delcabo** [comment]
sorry la pantalla de mi Tio... se me fue.... :)

**Comment by knonomura** [comment]
Your issue is opened in griddb/griddb_nosql repository,
but I guess it is a topic for another repository.
