### ISSUE TITLE
New cluster configuration methods in V3.0 not available

### ISSUE THREAD

**Issue by yk0310** [griddb/griddb_nosql#8]
When I set fixed list method, the following warning occurred.
WARNING MAIN [100002:CT_PARAMETER_INVALID] Unknown parameter (source=gs_cluster.json, group=cluster, name=notificationMember)

**Comment by knonomura** [comment]
I'm sorry, but Makefile is wrong.
Please wait for a while.

**Comment by knonomura** [comment]
I modified server/Makefile.am for new cluster configure methods.

**Comment by yk0310** [comment]
Thanks. I could start the server
