### ISSUE TITLE
Hello every one i'm stuck in my project with .NETCORE and angular 5 default templet in visul studio 2017.  i have created a form but bootstrap classes are not working..? any solution please. 

### ISSUE THREAD

**Issue by Awais2017** [griddb/griddb_nosql#81]

**Comment by Awais2017** [comment]
![Screenshot (17)](https://user-images.githubusercontent.com/33341040/54087522-71bda780-4375-11e9-91b2-97a7fb231bdf.png)

 any solution how should i import bootstrap.  
i have try by using @import '~bootstrap/dist/css/bootstrap.css'; but it  did't work.

**Comment by knonomura** [comment]
Thank you for your access.

Your issue is opened in griddb/griddb_nosql repository,
but I guess it is another topic.
