### ISSUE TITLE
How should i passs viewmodel in WebApi in .NetCore 2.0 .

### ISSUE THREAD

**Issue by Awais2017** [griddb/griddb_nosql#87]
[HttpGet("/api/users/get")]
        public async Task<IEnumerable<UserViewModel>> GetUser()
        {
            var Stations = context.Station.ToList();
            var Role = context.Roles.ToList();
            var Status = context.Status.ToList();
            var ViewModel = new UserViewModel {
                Stations=Stations,
                Roles=Role,
                Statuses=Status
            };
        }

**Comment by knonomura** [comment]
Your issue is opened in griddb/griddb_nosql repository,
but I guess it is another topic.
So, I close this issue.
