### ISSUE TITLE
Does the griddb  TQL support group by ?

### ISSUE THREAD

**Issue by ziflyingyo** [griddb/griddb_nosql#88]
Does the griddb  TQL support group by ?

**Comment by knonomura** [comment]
TQL don't support group by.

TQL support the following syntax:
[EXPLAIN [ANALYZE]] SELECT (select expression) [FROM (Collection or TimeSeries name)]  [WHERE (conditional expression)] ORDER BY (Column name) [ASC|DESC] [, (Column name) [ASC|DESC]]* [LIMIT (number) [OFFSET (number)]]

Please refer to 
http://griddb.org/griddb_nosql/manual/GridDB_API_Reference.html#sec-3-1

P.S.
If GridDB Advanced edition (commercial), it supports SQL with group by.
