### ISSUE TITLE
if else drop down menu

### ISSUE THREAD

**Issue by Joanapouzeiro** [griddb/griddb_nosql#91]
Hi

i am making a form and i am stuck here.
i have two drop down lists
=
<label required for="loc-select"><b>City:</b></label>
<select required name="City">
     <option></option><br>
        <option value="BE">BELGIUM</option>
        <option value="NL">NEDERLAND</option>
        <option value="HAM">HAMBURG</option>
        <option value="FR">FRANCE</option>
        </select>
    <p></p>
    <label required for="loc-select"><b>Location:</b></label>
<select required name="pc">
     <option></option><br>
        <option value="BE">LAPTOP</option>
        <option value="BE">DESKTOP</option>
        <option value="BE">IPAD</option>
        <option value="NL">LAPTOP</option>
        <option value="NL">DESKTOP</option>
        <option value="NL">IPAD</option>
        <option value="HAM">DESKTOP</option>
        <option value="FR">DESKTOP</option>
            </select>

now i want the option that if i click on city Belgium, it only show the option in dropdown menu PC with value BE, but i seems to be doing something really wrong :(

can someone help me?

**Comment by knonomura** [comment]
Thank you for your access.

Your issue is opened in griddb/griddb_nosql repository,
but I guess it is another topic.

**Comment by knonomura** [comment]
I close this issues as it is not related to this repository.
