### ISSUE TITLE
DVWA on Kali Linux

### ISSUE THREAD

**Issue by BlindMonkeyPL** [griddb/griddb_nosql#97]

**Comment by BlindMonkeyPL** [comment]
Hi there. I have problem with DVWA. DVWA server shows message : "Could not connect to MySQL server. Please chcek the conifg file." I have tried to fix it several times but it still does not work.  How can i solve this?

**Comment by knonomura** [comment]
Thank you for your access.

Your issue is opened in griddb/griddb_nosql repository,
but I guess it is another topic.

**Comment by BlindMonkeyPL** [comment]
Yea you right
