### ISSUE TITLE
Arch linux "disappear"

### ISSUE THREAD

**Issue by shadowkill991639** [griddb/griddb_nosql#98]
Hi everyone.

Every time I unplug the ssd where is installed arch linux or I boot another OS (installed on the same ssd or on another device) my bios doesn't "see" Arch linux anymore. The partitions I created where is installed arch aren't deleted and seems to contain all the datas. Someone knows why it happens and how to solve my problem?

**Comment by knonomura** [comment]
Thank you for your access.

Your issue is opened in griddb/griddb_nosql repository,
but I guess it is another topic.

**Comment by knonomura** [comment]
I close this issues as it is not related to this repository.
